// GENERATED by `cargo xtask ts-sdk`. Do not edit — regenerate.
//
// Source: the same schemas the Rust implementation is checked against, so a
// protocol change that forgets this file fails CI rather than a user's build.

export interface ModelList {
  object: "list";
  data: Model[];
}

export interface Model {
  /**
   * `provider/model`
   */
  id: string;
  object: "model";
  owned_by?: string;
}

/**
 * The subset of the standard dialect this ingress reads. Fields not listed are accepted and ignored rather than rejected — a client should not have to strip its request to be redirected here.
 */
export interface ChatCompletionRequest {
  /**
   * `provider/model`, or `auto` to route by policy (docs/12).
   */
  model: string;
  messages: Message[];
  /**
   * Server-sent events, ending with `data: [DONE]`.
   */
  stream?: boolean;
  temperature?: number;
  top_p?: number;
  max_tokens?: number;
  /**
   * A string or an array; both shapes appear in the wild.
   */
  stop?: string | string[];
}

export interface Message {
  role: "system" | "user" | "assistant" | "tool";
  /**
   * Absent on an assistant message that carried only tool calls.
   */
  content?: string | null;
}

export interface ChatCompletion {
  id: string;
  object: "chat.completion";
  created: number;
  /**
   * The model that actually answered, which is not necessarily the one requested: `auto` resolves through policy, and a failover walks the chain.
   */
  model: string;
  choices: Choice[];
  usage?: Usage;
}

export interface Choice {
  index: number;
  message: Message;
  finish_reason: "stop" | "length" | "tool_calls" | "content_filter";
}

export interface Usage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
}

export interface ErrorResponse {
  error: {
    message: string;
    type: "authentication_error" | "rate_limit_error" | "invalid_request_error" | "api_error";
  };
}

