// GENERATED by `cargo xtask ts-sdk`. Do not edit — regenerate.
//
// Source: the same schemas the Rust implementation is checked against, so a
// protocol change that forgets this file fails CI rather than a user's build.

import type { ChatCompletion, ChatCompletionRequest, ErrorResponse } from "./api.ts";

export interface PandayOptions {
  /** e.g. http://127.0.0.1:8088 — no trailing slash. */
  baseUrl: string;
  /** `pnd_live_…` or `pnd_test_…`. Omit against a gateway running without auth. */
  apiKey?: string;
  /** Defaults to the global `fetch`. Injectable so a test does not need a server. */
  fetch?: typeof fetch;
}

/** A refusal from the gateway, carrying the status the caller has to branch on. */
export class PandayError extends Error {
  constructor(
    readonly status: number,
    readonly type: string,
    message: string,
  ) {
    super(message);
    this.name = "PandayError";
  }
}

export class Panday {
  #options: PandayOptions;

  constructor(options: PandayOptions) {
    this.#options = options;
  }

  /** A non-streaming completion. */
  async chat(request: ChatCompletionRequest): Promise<ChatCompletion> {
    const response = await this.#post({ ...request, stream: false });
    return (await response.json()) as ChatCompletion;
  }

  /**
   * A streaming completion, as an async iterator of raw SSE payloads.
   *
   * Yields parsed JSON chunks and stops at the `[DONE]` sentinel, which is consumed rather than
   * yielded: it is framing, not data, and a caller that had to recognise it would be parsing the
   * transport.
   */
  async *stream(request: ChatCompletionRequest): AsyncGenerator<unknown> {
    const response = await this.#post({ ...request, stream: true });
    const body = response.body;
    if (!body) throw new PandayError(response.status, "api_error", "no response body");

    const reader = body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });

      // Frames are separated by a blank line. Split on that rather than on newlines, or a
      // multi-line frame is delivered as several broken ones.
      let boundary = buffer.indexOf("\n\n");
      while (boundary !== -1) {
        const frame = buffer.slice(0, boundary);
        buffer = buffer.slice(boundary + 2);
        boundary = buffer.indexOf("\n\n");

        for (const line of frame.split("\n")) {
          if (!line.startsWith("data:")) continue;
          const payload = line.slice(5).trim();
          if (payload === "[DONE]") return;
          yield JSON.parse(payload);
        }
      }
    }
  }

  async #post(request: ChatCompletionRequest): Promise<Response> {
    const doFetch = this.#options.fetch ?? fetch;
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (this.#options.apiKey) headers.authorization = `Bearer ${this.#options.apiKey}`;

    const response = await doFetch(`${this.#options.baseUrl}/v1/chat/completions`, {
      method: "POST",
      headers,
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      // Every failure arrives in the same envelope, so this is the only error path.
      const body = (await response.json().catch(() => null)) as ErrorResponse | null;
      throw new PandayError(
        response.status,
        body?.error?.type ?? "api_error",
        body?.error?.message ?? response.statusText,
      );
    }
    return response;
  }
}
