// GENERATED by `cargo xtask ts-sdk`. Do not edit — regenerate.
//
// Source: the same schemas the Rust implementation is checked against, so a
// protocol change that forgets this file fails CI rather than a user's build.

/**
 * UUIDv7, canonical hyphenated form
 */
export type SessionId = string;

/**
 * UUIDv7, canonical hyphenated form
 */
export type TurnId = string;

/**
 * Content is block-structured from day one so images/artifacts don't force
 * a protocol bump later.
 */
export type ContentBlock =
  | {
      text: string;
      type: "text";
    }
  | {
      call_id: CallId;
      text: string;
      /**
       * Where this text came from (docs/20 T1 §origin tagging).
       * 
       * Additive and optional (docs/03 §Versioning: "Additive fields: always
       * ok"), so an older log still reads. `None` means "not tagged", which
       * callers must treat as untrusted rather than as user input — a missing
       * tag on a tool output is a gap in provenance, not a promise.
       */
      origin?: Origin | null;
      type: "tool_output";
    }
  | {
      artifact: ArtifactRef;
      summary: string;
      origin?: Origin | null;
      type: "artifact";
    };

/**
 * UUIDv7, canonical hyphenated form
 */
export type CallId = string;

/**
 * Provenance of a context block (docs/20 T1: "every context block carries
 * provenance (user | tool:{name} | web:{domain} | plugin:{id}); the system prompt
 * and permission engine treat non-user origins as untrusted").
 * 
 * The distinction this exists to preserve is the one prompt injection attacks:
 * text the *user* wrote is an instruction, and text a *tool* returned is data
 * about the world. Both arrive as strings in the same conversation, so the
 * difference has to be carried rather than inferred.
 */
export type Origin =
  | {
      kind: "user";
    }
  | {
      kind: "system";
    }
  | {
      name: string;
      kind: "tool";
    }
  | {
      domain: string;
      kind: "web";
    }
  | {
      id: string;
      kind: "plugin";
    }
  | {
      server: string;
      tool: string;
      kind: "mcp";
    };

/**
 * Content-addressed handle into object storage. Events carry these instead
 * of large payloads (docs/03, docs/15).
 */
export interface ArtifactRef {
  /**
   * sha256 of content, hex.
   */
  hash: string;
  /**
   * Size in bytes of the raw artifact.
   */
  size: number;
  /**
   * MIME type where known.
   */
  media_type?: unknown;
}

export type ClientKind = "cli" | "acp" | "web" | "api" | "system";

/**
 * Token accounting with cache splits — the ledger prices these at different
 * rates: fresh input 1x; cache reads ~0.1x (both major providers); cache
 * writes are Anthropic-only surcharges at 1.25x (5-minute TTL) or 2x
 * (1-hour TTL) — OpenAI-style automatic caching has no write premium.
 * 
 * CONVENTION (normative, enforced at the adapter boundary): the cache
 * counts are SUBSETS of `input_tokens`. `input_tokens` is the total input;
 * `cache_read + cache_write_5m + cache_write_1h <= input_tokens`, and the
 * fresh remainder is the difference. Adapters for providers that report
 * disjoint counts (e.g. Anthropic reports cache reads/writes separately
 * from `input_tokens`) MUST normalize by adding them into `input_tokens`.
 */
export interface Usage {
  input_tokens: number;
  output_tokens: number;
  cache_read_tokens?: number;
  /**
   * Cache-write tokens at the short-TTL (5m-class) rate.
   */
  cache_write_tokens?: number;
  /**
   * Cache-write tokens at the extended-TTL (1h-class) rate — priced
   * differently (~2x vs ~1.25x); requested via `CacheHints::extended_ttl`.
   */
  cache_write_1h_tokens?: number;
}

/**
 * Reduced tool output as it enters context; the raw is in `raw_ref`.
 */
export interface ReducedOutput {
  text: string;
  tokens_raw: number;
  tokens_kept: number;
  /**
   * Which reducer strategy produced this (docs/15).
   */
  strategy: string;
}

export type PermDecision = "allow" | "allow_remember" | "deny";

export type Actor =
  | "user" | "system"
  | {
      policy: {
        rule: string;
      };
    };

/**
 * A model reference: `provider/model` (e.g. `anthropic/claude-sonnet-5`,
 * `xai/grok-4.6`) or the literal `auto` to let the router decide.
 */
export type ModelRef = string;

export type StopReason = "end_turn" | "tool_use" | "max_tokens" | "stop_sequence" | "cancelled" | "budget_exceeded" | "max_steps" | "error";

/**
 * Every event on the wire and in the log wears this envelope.
 */
export interface Envelope {
  /**
   * Protocol version. Bump rules in docs/03 §Versioning.
   */
  v: number;
  session_id: SessionId;
  /**
   * Gapless, per-session. THE ordering primitive; clients resume with
   * `after_seq`.
   */
  seq: number;
  turn_id?: TurnId | null;
  /**
   * RFC 3339 UTC timestamp
   */
  at: string;
}

