//! Repo automation. docs/02 §Toolchain: "`cargo xtask` pattern for codegen
//! (event-schema export, OpenAPI generation) instead of build.rs cleverness."
//!
//! ```text
//! cargo xtask schemas          # regenerate proto/
//! cargo xtask schemas --check  # fail if proto/ is stale (CI)
//! cargo xtask reduce-bench     # reduce-then-solve scorecard + regression gate
//! cargo xtask wasm-fixtures    # rebuild the checked-in T1 plugin components
//! cargo xtask scorecard        # the weekly review artifact (docs/12 M12.4, docs/19)
//! ```

use std::path::{Path, PathBuf};
use std::process::ExitCode;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (cmd, rest) = match args.split_first() {
        Some((c, r)) => (c.as_str(), r),
        None => {
            usage();
            return ExitCode::FAILURE;
        }
    };

    match cmd {
        "schemas" => {
            let check = rest.iter().any(|a| a == "--check");
            match schemas(check) {
                Ok(code) => code,
                Err(e) => {
                    eprintln!("xtask schemas: {e}");
                    ExitCode::FAILURE
                }
            }
        }
        // M15.5. A task rather than only a test so the nightly job has one thing
        // to run and one artifact to keep, and so a human can read the scorecard
        // without decoding `cargo test` output.
        "reduce-bench" => reduce_bench(rest.iter().any(|a| a == "--quiet")),
        // M14.4. The built components are checked in, so this is run by a human
        // when a fixture's source changes — not by CI, which must not need a wasm
        // toolchain to gate the sandbox.
        // M12.4. Calls the evals as libraries rather than parsing test output: a report
        // assembled from `cargo test` stdout breaks the first time someone renames a test.
        "scorecard" => match scorecard(rest.iter().any(|a| a == "--write")) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask scorecard: {e}");
                ExitCode::FAILURE
            }
        },
        "wasm-fixtures" => match wasm_fixtures() {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask wasm-fixtures: {e}");
                ExitCode::FAILURE
            }
        },
        "help" | "--help" | "-h" => {
            usage();
            ExitCode::SUCCESS
        }
        other => {
            eprintln!("unknown task: {other}\n");
            usage();
            ExitCode::FAILURE
        }
    }
}

fn usage() {
    eprintln!(
        "usage: cargo xtask <task>\n\n\
         tasks:\n  \
         schemas [--check]   export JSON Schema for the event protocol to proto/\n  \
         reduce-bench        run the reduce-then-solve eval; non-zero on regression\n  \
         wasm-fixtures       rebuild fixtures/*-tool into the T1 test fixtures\n  \
         scorecard [--write] the weekly eval scorecard; --write saves it under scorecards/\n"
    );
}

/// The weekly review artifact (docs/12 M12.4, docs/19 §gates).
///
/// > "Scorecard generator from eval runs; the weekly review is a generated PR against the
/// > YAML."
///
/// Two halves. This produces the *report*, from the evals that exist as libraries
/// (`panday_router::bench`, `panday_harness::eval`) — not by parsing test output, which breaks
/// the first time someone renames a test. `.github/workflows/weekly-review.yml` is the other
/// half: it runs this, commits the file, and opens the PR a human reviews.
///
/// What it deliberately does **not** do is edit the policy YAML itself. Removing a rule
/// changes where traffic goes, and a generator that did that silently would be the one
/// component in this repo making routing decisions nobody reviewed. It reports what the
/// linter found and leaves the edit in the PR's hands.
fn scorecard(write: bool) -> Result<ExitCode, String> {
    let root = repo_root();
    let mut out = String::new();
    let today = std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%d"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "undated".into());

    out.push_str(&format!("# Scorecard — {today}\n\n"));
    out.push_str(
        "Generated by `cargo xtask scorecard` (docs/12 M12.4). Every number here comes from an\n\
         eval that also gates CI, so this report and the test suite cannot disagree.\n\n",
    );

    // route-bench (docs/19's task-classification suite).
    out.push_str("## route-bench — task classification\n\n");
    let heuristic = panday_router::bench::score(&panday_router::classify::HeuristicClassifier);
    out.push_str("```\n");
    out.push_str(&heuristic.scorecard("heuristic"));
    out.push_str("```\n\n");
    out.push_str(&format!(
        "Gate (docs/19): accuracy >= 70% and never confidently wrong — **{}**.\n\n",
        if heuristic.meets_the_gate(0.70) {
            "pass"
        } else {
            "FAIL"
        }
    ));
    out.push_str(
        "The trained classifier (M19.3) must beat this by >=10pt on the same corpus; \
         `panday_router::shadow` is how a candidate is compared without letting it route.\n\n",
    );

    // The routing policy's own lint.
    out.push_str("## routing policy\n\n");
    for policy in ["default.yaml", "dev.yaml", "local.yaml"] {
        let path = root.join("crates/panday-router/policy").join(policy);
        let text =
            std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        match panday_router::Policy::from_yaml(&text) {
            Ok(parsed) => {
                let findings = parsed.lint();
                if findings.is_empty() {
                    out.push_str(&format!("- `{policy}`: no unreachable rules.\n"));
                } else {
                    out.push_str(&format!(
                        "- `{policy}`: **{} finding(s)**\n",
                        findings.len()
                    ));
                    for finding in findings {
                        out.push_str(&format!(
                            "  - rules[{}]: {}\n",
                            finding.rule_index, finding.message
                        ));
                    }
                }
            }
            Err(e) => out.push_str(&format!("- `{policy}`: **does not parse** — {e}\n")),
        }
    }
    out.push_str(
        "\nA finding here is a rule that can never fire, which means traffic is going \
         somewhere other than where the file says. The fix is a YAML edit, and it is left to \
         the human reading this PR — a generator that rewrote routing on its own would be the \
         one component here making a decision nobody reviewed.\n\n",
    );

    out.push_str("## reduce-bench — reduce-then-solve\n\n");
    out.push_str(
        "Run by `cargo xtask reduce-bench` (M15.5) and by the nightly job; it needs an async \
         runtime, so it is a separate task rather than a section here. Its gate — no recorded \
         task may become unsolvable — blocks release on its own.\n\n",
    );

    out.push_str("## what is not measured yet\n\n");
    out.push_str(
        "- `agent-bench` (M19.6): 50 verifiable repo tasks. Needs T3 (M14.5).\n\
         - `json-bench` (M19.1): schema-validity rates.\n\
         - Capability profiles (M18.4) ship **declared**, not measured; M19.2 measures them, \
         and until then every profile says `(estimated)` in the system prompt.\n",
    );

    print!("{out}");

    if write {
        let dir = root.join("scorecards");
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let path = dir.join(format!("{today}.md"));
        std::fs::write(&path, &out).map_err(|e| format!("{}: {e}", path.display()))?;
        eprintln!("wrote {}", path.display());
    }

    // The exit code is the gate, so a workflow can use it directly.
    Ok(if heuristic.meets_the_gate(0.70) {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    })
}

/// Rebuild the T1 demo components and copy them where the escape suite reads them.
///
/// The output is checked in on purpose (see `crates/panday-sandbox/tests/t1_wasm.rs`):
/// a suite that needed `wasm32-wasip2` and `cargo-component` installed would skip
/// itself on most machines, and a sandbox suite that skips itself is a sandbox
/// nobody is testing.
fn wasm_fixtures() -> Result<ExitCode, String> {
    const TARGET: &str = "wasm32-wasip2";
    let root = repo_root();
    let dest = root.join("crates/panday-sandbox/tests/fixtures");
    std::fs::create_dir_all(&dest).map_err(|e| e.to_string())?;

    for (dir, artifact) in [
        ("fixtures/demo-tool", "demo_tool.wasm"),
        ("fixtures/greedy-tool", "greedy_tool.wasm"),
        ("fixtures/demo-hook", "demo_hook.wasm"),
    ] {
        let crate_dir = root.join(dir);
        let status = std::process::Command::new(env!("CARGO"))
            .current_dir(&crate_dir)
            .args(["build", "--release", "--target", TARGET])
            .status()
            .map_err(|e| format!("{dir}: {e}"))?;
        if !status.success() {
            return Err(format!(
                "{dir}: build failed (is the {TARGET} target installed? \
                 `rustup target add {TARGET}`)"
            ));
        }
        let built = crate_dir
            .join("target")
            .join(TARGET)
            .join("release")
            .join(artifact);
        std::fs::copy(&built, dest.join(artifact))
            .map_err(|e| format!("copy {}: {e}", built.display()))?;
        println!("{} -> {}", built.display(), dest.join(artifact).display());
    }
    println!(
        "\nThe components are checked in; commit them with the change that \
         produced them so a reviewer sees both."
    );
    Ok(ExitCode::SUCCESS)
}

/// docs/15 M15.5: "nightly job + regression gate". The gate is the exit code.
fn reduce_bench(quiet: bool) -> ExitCode {
    // Delegating to the test binary rather than reimplementing the corpus here:
    // two copies of an eval corpus drift, and the copy the gate runs would be
    // the one nobody looks at.
    let status = std::process::Command::new(env!("CARGO"))
        .current_dir(repo_root())
        .args([
            "test",
            "-p",
            "panday-harness",
            "--test",
            "reduce_then_solve",
            "--",
            "--nocapture",
        ])
        .args(if quiet { vec!["--quiet"] } else { vec![] })
        .status();

    match status {
        Ok(s) if s.success() => ExitCode::SUCCESS,
        Ok(_) => {
            eprintln!(
                "\nreduce-bench FAILED — reduction made a recorded task unsolvable.\n\
                 docs/15: \"a reducer that loses the plot is negative value at any \
                 compression ratio\". This blocks release."
            );
            ExitCode::FAILURE
        }
        Err(e) => {
            eprintln!("reduce-bench: cannot run cargo test: {e}");
            ExitCode::FAILURE
        }
    }
}

fn repo_root() -> PathBuf {
    // xtask/ lives one level below the workspace root.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must live under the workspace root")
        .to_path_buf()
}

/// The schemas we publish, and where. Adding an entry here is all it takes to
/// export another type.
fn targets() -> Vec<(&'static str, schemars::Schema)> {
    vec![(
        "aep-envelope.schema.json",
        schemars::schema_for!(panday_types::Envelope),
    )]
}

fn render(schema: &schemars::Schema) -> Result<String, String> {
    let mut s = serde_json::to_string_pretty(schema).map_err(|e| e.to_string())?;
    s.push('\n');
    Ok(s)
}

fn schemas(check: bool) -> Result<ExitCode, String> {
    let dir = repo_root().join("proto");
    std::fs::create_dir_all(&dir).map_err(|e| format!("create proto/: {e}"))?;

    let mut stale = Vec::new();
    for (name, schema) in targets() {
        let path = dir.join(name);
        let generated = render(&schema)?;

        if check {
            let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
            if on_disk != generated {
                stale.push(name);
            }
        } else {
            std::fs::write(&path, &generated).map_err(|e| format!("write {name}: {e}"))?;
            println!("wrote proto/{name}");
        }
    }

    if check && !stale.is_empty() {
        eprintln!(
            "proto/ is out of date: {stale:?}\n\n\
             The event protocol changed without regenerating its schema. Run:\n  \
             cargo xtask schemas\n\n\
             and include a version note per docs/03 §Versioning discipline — a\n\
             schema change without one is a breaking change nobody reviewed."
        );
        return Ok(ExitCode::FAILURE);
    }

    if check {
        println!("proto/ is up to date");
    }
    Ok(ExitCode::SUCCESS)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exported schema must describe every event kind this build knows.
    /// Without this, adding an `Event` variant that schemars silently skips
    /// would ship a schema that rejects valid traffic.
    #[test]
    fn schema_describes_every_known_event_tag() {
        let schema = serde_json::to_string(&schemars::schema_for!(panday_types::Envelope))
            .expect("schema serializes");

        let missing: Vec<&str> = panday_types::event::KNOWN_EVENT_TAGS
            .iter()
            .copied()
            .filter(|tag| !schema.contains(&format!("\"const\":\"{tag}\"")))
            .collect();

        assert!(
            missing.is_empty(),
            "these event kinds are missing from the exported schema: {missing:?}"
        );
    }

    /// Schema generation must be deterministic, or `--check` would flap in CI
    /// and every run would look like a protocol change.
    #[test]
    fn schema_generation_is_stable() {
        let a = render(&schemars::schema_for!(panday_types::Envelope)).unwrap();
        let b = render(&schemars::schema_for!(panday_types::Envelope)).unwrap();
        assert_eq!(a, b, "schema generation is not deterministic");
    }
}
