//! Repo automation. docs/02 §Toolchain: "`cargo xtask` pattern for codegen
//! (event-schema export, OpenAPI generation) instead of build.rs cleverness."
//!
//! ```text
//! cargo xtask schemas          # regenerate proto/
//! cargo xtask schemas --check  # fail if proto/ is stale (CI)
//! cargo xtask reduce-bench     # reduce-then-solve scorecard + regression gate
//! cargo xtask wasm-fixtures    # rebuild the checked-in T1 plugin components
//! cargo xtask scorecard        # the weekly review artifact (docs/12 M12.4, docs/19)
//! ```

use std::path::{Path, PathBuf};
use std::process::ExitCode;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (cmd, rest) = match args.split_first() {
        Some((c, r)) => (c.as_str(), r),
        None => {
            usage();
            return ExitCode::FAILURE;
        }
    };

    match cmd {
        "schemas" => {
            let check = rest.iter().any(|a| a == "--check");
            match schemas(check) {
                Ok(code) => code,
                Err(e) => {
                    eprintln!("xtask schemas: {e}");
                    ExitCode::FAILURE
                }
            }
        }
        // M15.5. A task rather than only a test so the nightly job has one thing
        // to run and one artifact to keep, and so a human can read the scorecard
        // without decoding `cargo test` output.
        "reduce-bench" => reduce_bench(rest.iter().any(|a| a == "--quiet")),
        // M14.4. The built components are checked in, so this is run by a human
        // when a fixture's source changes — not by CI, which must not need a wasm
        // toolchain to gate the sandbox.
        // M12.4. Calls the evals as libraries rather than parsing test output: a report
        // assembled from `cargo test` stdout breaks the first time someone renames a test.
        "scorecard" => match scorecard(rest.iter().any(|a| a == "--write")) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask scorecard: {e}");
                ExitCode::FAILURE
            }
        },
        // M20.5. Regenerated by a human when dependencies change and checked in, so a diff of
        // `sbom.cdx.json` in a PR is the dependency review; CI re-runs it with `--check` so the
        // file cannot drift from the lockfile.
        "sbom" => match sbom(rest.iter().any(|a| a == "--check")) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask sbom: {e}");
                ExitCode::FAILURE
            }
        },
        // M10.6. Generated from the schemas and the OpenAPI document, checked in, and re-checked
        // by CI: a protocol change that forgets the SDK breaks our build rather than a user's.
        "ts-sdk" => match ts_sdk(rest.iter().any(|a| a == "--check")) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask ts-sdk: {e}");
                ExitCode::FAILURE
            }
        },
        // M19.1. Needs a model, so it is never part of `just check`: a suite that skips when it
        // cannot measure reports a green tick for "we did not measure".
        "json-bench" => match json_bench(rest) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask json-bench: {e}");
                ExitCode::FAILURE
            }
        },
        // M18.7. Built by a human on a release commit, carried in on a USB stick, and unpacked on
        // a machine with no internet.
        "airgap" => match airgap(rest) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask airgap: {e}");
                ExitCode::FAILURE
            }
        },
        // M19.4. Reads session logs, writes training examples, and refuses anything without
        // recorded consent.
        "mine" => match mine(rest) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask mine: {e}");
                ExitCode::FAILURE
            }
        },
        // M19.2. Measures a model through the gateway and prints the catalog entry to paste.
        "profile" => match profile(rest) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask profile: {e}");
                ExitCode::FAILURE
            }
        },
        "wasm-fixtures" => match wasm_fixtures() {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask wasm-fixtures: {e}");
                ExitCode::FAILURE
            }
        },
        "help" | "--help" | "-h" => {
            usage();
            ExitCode::SUCCESS
        }
        other => {
            eprintln!("unknown task: {other}\n");
            usage();
            ExitCode::FAILURE
        }
    }
}

fn usage() {
    eprintln!(
        "usage: cargo xtask <task>\n\n\
         tasks:\n  \
         schemas [--check]   export JSON Schema for the event protocol to proto/\n  \
         reduce-bench        run the reduce-then-solve eval; non-zero on regression\n  \
         wasm-fixtures       rebuild fixtures/*-tool into the T1 test fixtures\n  \
         scorecard [--write] the weekly eval scorecard; --write saves it under scorecards/\n  \
         sbom [--check]      write sbom.cdx.json from the lockfile; --check fails on drift\n  \
         ts-sdk [--check]    regenerate sdk/typescript/ and proto/openapi.json\n  \
         json-bench          schema-validity against a running gateway; needs a model\n  \
         airgap [--models <dir>] [--out <dir>]  build the offline install kit (M18.7)\n  \
         mine --logs <dir> --out <file> [--consent granted]  mine training pairs (M19.4)\n  \
         profile --model <ref> [--base-url <url>] [--ceiling <tokens>]  measure a model (M19.2)\n"
    );
}

mod sbom;
mod sdk;
mod ts;

/// Measure a model's real capabilities (docs/19 M19.2).
///
/// Prints a catalog entry rather than editing the catalog. A measurement rewriting a checked-in
/// routing table unattended is one model's bad afternoon silently becoming everyone's routing
/// decisions; a person pastes it, and the diff is the review.
fn profile(args: &[String]) -> Result<ExitCode, String> {
    let flag = |name: &str| -> Option<String> {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1))
            .cloned()
    };
    let model = flag("--model").ok_or("--model <provider/model> is required")?;
    let base_url = flag("--base-url").unwrap_or_else(|| "http://127.0.0.1:8088".to_string());
    let ceiling: u32 = flag("--ceiling")
        .and_then(|v| v.parse().ok())
        .unwrap_or(65_536);
    let at = flag("--at").unwrap_or_else(|| "unstamped".to_string());

    let runtime = tokio::runtime::Runtime::new().map_err(|e| e.to_string())?;
    let measured = runtime.block_on(async {
        let client = panday_sdk::providers::openai_compat::OpenAiCompatClient::new(
            &base_url,
            std::env::var("PANDAY_API_KEY").ok(),
        );
        let model_ref = panday_types::model::ModelRef(model.clone());
        // The declared profile supplies only what a text probe cannot reach — vision and subagent
        // fan-out. Everything else is measured or reported as zero.
        let declared = panday_types::capability::CapabilityProfile::small_local();
        panday_harness::profiling::measure(&client, &model_ref, declared, ceiling).await
    });

    let model_ref = panday_types::model::ModelRef(model);
    print!(
        "{}",
        panday_harness::profiling::to_yaml(&model_ref, &measured, &at)
    );

    if measured.profile.max_context_tokens == 0 {
        // A model that failed the smallest context probe is not a model this measurement can
        // describe, and emitting a profile of zeroes as if it were a result would be worse than
        // saying so.
        return Err("the model answered nothing at any context size — is it running?".into());
    }
    Ok(ExitCode::SUCCESS)
}

/// Transcript mining (docs/19 M19.4).
///
/// Consent is a flag on this command rather than a lookup, and it defaults to *unknown* — which
/// mines nothing. A pipeline that inferred consent from where a log happened to be stored would be
/// one directory move away from a breach, and the operator asserting it here is a person who can be
/// asked what they based it on.
fn mine(args: &[String]) -> Result<ExitCode, String> {
    use panday_harness::mining::{summarizer_pairs, Consent, MiningReport};

    let flag = |name: &str| -> Option<String> {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1))
            .cloned()
    };
    let logs = flag("--logs").ok_or("--logs <dir> is required")?;
    let out = flag("--out").ok_or("--out <file.jsonl> is required")?;
    let consent = match flag("--consent").as_deref() {
        Some("granted") => Consent::Granted,
        Some("denied") => Consent::Denied,
        Some(other) => return Err(format!("--consent granted|denied, got `{other}`")),
        None => Consent::Unknown,
    };

    let scrub = |text: &str| panday_harness::mining::scrub_shapes(text);
    let mut total = MiningReport::default();
    let mut written = 0usize;
    let mut file = String::new();

    let mut paths: Vec<PathBuf> = std::fs::read_dir(&logs)
        .map_err(|e| format!("read {logs}: {e}"))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "jsonl"))
        .collect();
    paths.sort();

    for path in &paths {
        let events =
            panday_harness::read_log(path).map_err(|e| format!("{}: {e}", path.display()))?;
        let (examples, report) = summarizer_pairs(&events, consent, &scrub);
        total.examples += report.examples;
        total.skipped_no_consent += report.skipped_no_consent;
        total.skipped_still_sensitive += report.skipped_still_sensitive;
        total.skipped_too_short += report.skipped_too_short;

        for example in examples {
            file.push_str(&serde_json::to_string(&example).map_err(|e| e.to_string())?);
            file.push('\n');
            written += 1;
        }
    }

    std::fs::write(&out, file).map_err(|e| format!("write {out}: {e}"))?;
    println!(
        "{} log(s) → {written} example(s) in {out}\n  \
         skipped: {} without consent, {} still sensitive after scrubbing, {} not a reduction",
        paths.len(),
        total.skipped_no_consent,
        total.skipped_still_sensitive,
        total.skipped_too_short
    );
    // Nothing mined is not an error — an operator running this over logs nobody consented to should
    // see zero and a reason, not a failure they will be tempted to work around.
    Ok(ExitCode::SUCCESS)
}

/// The air-gap kit (docs/18 M18.7).
///
/// > "one tarball (binary + catalog + models) installs on a machine with no internet; documented
/// > for enterprise."
///
/// Assembles a directory and leaves the tarring to `tar`, on purpose: an enterprise operator is
/// going to inspect this before carrying it through a door, and a directory they can `ls` is one
/// they can review. The kit is deliberately *complete or absent* — a kit missing its models
/// installs and then fails at the first prompt, which is the worst possible place to discover it.
fn airgap(args: &[String]) -> Result<ExitCode, String> {
    let flag = |name: &str| -> Option<String> {
        args.iter()
            .position(|a| a == name)
            .and_then(|i| args.get(i + 1))
            .cloned()
    };
    let root = repo_root();
    let out = PathBuf::from(
        flag("--out").unwrap_or_else(|| root.join("target/airgap").display().to_string()),
    );
    let models = flag("--models");

    // Release binaries, from this tree. Not built here: `cargo build --release` on a machine that
    // is not the release machine is how an air-gap bundle ends up with a debug build in it.
    let release = root.join("target/release");
    let binaries = [
        "panday",
        "panday-local",
        "panday-gateway",
        "panday-platform",
    ];
    let missing: Vec<&str> = binaries
        .iter()
        .copied()
        .filter(|b| !release.join(b).is_file())
        .collect();
    if !missing.is_empty() {
        return Err(format!(
            "missing release binaries: {missing:?}\n  build them first: cargo build --release"
        ));
    }

    let _ = std::fs::remove_dir_all(&out);
    std::fs::create_dir_all(out.join("bin")).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(out.join("models")).map_err(|e| e.to_string())?;

    for binary in binaries {
        std::fs::copy(release.join(binary), out.join("bin").join(binary))
            .map_err(|e| format!("copy {binary}: {e}"))?;
    }

    // The policy and the catalog: a machine with no internet still routes and still knows what its
    // models are.
    std::fs::create_dir_all(out.join("config")).map_err(|e| e.to_string())?;
    for (name, source) in [
        (
            "local.yaml",
            root.join("crates/panday-router/policy/local.yaml"),
        ),
        (
            "catalog.yaml",
            root.join("crates/panday-router/catalog/default.yaml"),
        ),
    ] {
        std::fs::copy(&source, out.join("config").join(name))
            .map_err(|e| format!("copy {name}: {e}"))?;
    }

    let mut model_files = Vec::new();
    if let Some(dir) = &models {
        for entry in std::fs::read_dir(dir).map_err(|e| format!("read {dir}: {e}"))? {
            let path = entry.map_err(|e| e.to_string())?.path();
            if path.extension().is_some_and(|e| e == "gguf") {
                let name = path
                    .file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string();
                std::fs::copy(&path, out.join("models").join(&name))
                    .map_err(|e| format!("copy {name}: {e}"))?;
                model_files.push(name);
            }
        }
        if model_files.is_empty() {
            return Err(format!("no .gguf files in {dir} — a kit without a model installs and then fails at the first prompt"));
        }
    }

    std::fs::write(out.join("INSTALL.md"), install_readme(&model_files))
        .map_err(|e| e.to_string())?;
    std::fs::write(out.join("install.sh"), INSTALL_SH).map_err(|e| e.to_string())?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(
            out.join("install.sh"),
            std::fs::Permissions::from_mode(0o755),
        )
        .map_err(|e| e.to_string())?;
    }

    println!(
        "kit assembled at {}\n  binaries: {}\n  models:   {}\n\n  tar -czf panday-airgap.tar.gz -C {} .",
        out.display(),
        binaries.join(", "),
        if model_files.is_empty() {
            "none — pass --models <dir> to include GGUFs".to_string()
        } else {
            model_files.join(", ")
        },
        out.display()
    );
    Ok(ExitCode::SUCCESS)
}

const INSTALL_SH: &str = r#"#!/usr/bin/env sh
# Panday air-gap installer (docs/18 M18.7). No network, by design.
set -eu

PREFIX="${PREFIX:-$HOME/.local}"
MODEL_DIR="${PANDAY_MODEL_DIR:-$HOME/.panday/models}"
HERE="$(cd "$(dirname "$0")" && pwd)"

mkdir -p "$PREFIX/bin" "$MODEL_DIR" "$HOME/.panday"
cp "$HERE"/bin/* "$PREFIX/bin/"
cp "$HERE"/config/* "$HOME/.panday/"

# Copied rather than linked: a USB stick that gets unplugged is not a storage backend.
if [ -d "$HERE/models" ] && [ -n "$(ls -A "$HERE/models" 2>/dev/null)" ]; then
  cp "$HERE"/models/*.gguf "$MODEL_DIR/"
fi

echo "installed to $PREFIX/bin"
echo "models in    $MODEL_DIR"
echo
echo "Check it works, with nothing plugged in:"
echo "  $PREFIX/bin/panday-local --serve $MODEL_DIR/<model>.gguf --workspace . 'say hello'"
"#;

fn install_readme(models: &[String]) -> String {
    let model_list = if models.is_empty() {
        "*(this kit ships no models — the machine will need one before `panday local` can answer)*"
            .to_string()
    } else {
        models
            .iter()
            .map(|m| format!("- `{m}`"))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"# Panday — air-gapped install

Everything needed to run Panday on a machine with no internet connection. Nothing in here reaches
the network: not the installer, not the first run, not the agent (ADR-011).

## What is in the box

```
bin/       panday, panday-local, panday-gateway, panday-platform
config/    local.yaml (routing), catalog.yaml (models)
models/    the GGUFs this kit was built with
INSTALL.md this file
install.sh copies the above into place
```

Models included:

{model_list}

## Install

```sh
./install.sh                 # into ~/.local/bin and ~/.panday/models
PREFIX=/opt/panday ./install.sh   # or somewhere else
```

The installer copies rather than links, because a USB stick that gets unplugged is not a storage
backend.

## Verify it, offline

```sh
panday-local --serve ~/.panday/models/<model>.gguf --workspace . "say hello"
```

`panday local` refuses any base URL that is not loopback, so if the machine later gains a network,
the offline tier still cannot reach it.

## Licensing

An entitlement token is a file (docs/17 M17.6). Copy it and its `.sig` onto the machine and run:

```sh
PANDAY_ENTITLEMENT_KEY=<the public key you were given>   panday-local --entitlement ~/.panday/licence.json --workspace . "…"
```

Verification is local: no activation, no call home, no revocation check. When it expires the
software keeps working at the community tier rather than stopping — a renewal is a new file.

## Updating

Bring a newer kit and run `install.sh` again. The event logs under `.panday/` are append-only and
are not touched by an install (ADR-002).

## What this kit does not include

- **A cloud account.** None is needed; the offline tier works without one.
- **A model catalog signature.** `catalog.yaml` here is the routing catalog. The *signed model
  index* (`panday models`) is for machines that can download; on an air-gapped box the models are
  already in `models/`.
"#
    )
}

/// `json-bench` against a running gateway (docs/19 M19.1).
///
/// Against the *gateway*, not a provider: the eval exercises routing, caching and the adapter as
/// well as the model, which is docs/19's "three birds". The scorecard it writes is a committed
/// artifact, because a number nobody can point at later is a number nobody trusts.
fn json_bench(args: &[String]) -> Result<ExitCode, String> {
    let value = |flag: &str, default: &str| -> String {
        args.iter()
            .position(|a| a == flag)
            .and_then(|i| args.get(i + 1))
            .cloned()
            .unwrap_or_else(|| default.to_string())
    };
    let model = value("--model", "local/qwen3.5-4b");
    let base_url = value("--base-url", "http://127.0.0.1:8088");
    let at = value("--at", "unstamped");
    let quantization = args
        .iter()
        .position(|a| a == "--quantization")
        .and_then(|i| args.get(i + 1))
        .cloned();
    let write = args.iter().any(|a| a == "--write");

    let runtime = tokio::runtime::Runtime::new().map_err(|e| e.to_string())?;
    let card = runtime.block_on(async {
        // The gateway speaks the same dialect it accepts, so the eval reaches it with the same
        // client any customer would use (docs/11 M11.5) — no private path.
        let client = panday_sdk::providers::openai_compat::OpenAiCompatClient::new(
            &base_url,
            std::env::var("PANDAY_API_KEY").ok(),
        );
        let corpus = panday_harness::json_bench::corpus();
        let mut card = panday_harness::json_bench::run(
            &client,
            &panday_types::model::ModelRef(model.clone()),
            &model,
            &at,
            &corpus,
        )
        .await;
        // docs/19 §gates: "quantize → then eval". A scorecard that does not say which quantization
        // it measured cannot be compared to the artifact anyone actually runs.
        card.provenance.quantization = quantization;
        card
    });

    print!("{}", card.to_markdown());
    if write {
        let dir = repo_root().join("scorecards");
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let path = dir.join(format!(
            "json-bench-{}.json",
            card.subject.replace('/', "_")
        ));
        let mut json = serde_json::to_string_pretty(&card).map_err(|e| e.to_string())?;
        json.push('\n');
        std::fs::write(&path, json).map_err(|e| format!("write {}: {e}", path.display()))?;
        println!("\nwrote {}", path.display());
    }
    // Non-zero when the suite found nothing to measure, so a broken endpoint is not a silent pass.
    Ok(if card.cases > 0 {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    })
}

/// The generated TypeScript SDK and the OpenAPI document (docs/10 M10.6).
fn ts_sdk(check: bool) -> Result<ExitCode, String> {
    let root = repo_root();
    let envelope: serde_json::Value = {
        let path = root.join("proto/aep-envelope.schema.json");
        let raw = std::fs::read_to_string(&path).map_err(|e| {
            format!(
                "read {}: {e} — run `cargo xtask schemas` first",
                path.display()
            )
        })?;
        serde_json::from_str(&raw).map_err(|e| format!("{}: {e}", path.display()))?
    };

    let openapi = panday_gateway::openapi::document();
    let mut openapi_json = serde_json::to_string_pretty(&openapi).map_err(|e| e.to_string())?;
    openapi_json.push('\n');

    let mut outputs: Vec<(PathBuf, String)> = vec![(root.join("proto/openapi.json"), openapi_json)];
    for file in sdk::files(&envelope, &openapi)? {
        outputs.push((root.join("sdk/typescript").join(file.path), file.contents));
    }

    let mut stale = Vec::new();
    for (path, contents) in &outputs {
        if check {
            if std::fs::read_to_string(path).unwrap_or_default() != *contents {
                stale.push(path.display().to_string());
            }
            continue;
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create {}: {e}", parent.display()))?;
        }
        std::fs::write(path, contents).map_err(|e| format!("write {}: {e}", path.display()))?;
    }

    if check {
        if !stale.is_empty() {
            eprintln!(
                "the generated SDK is stale: {stale:?}\n\n\
                 The protocol or the HTTP surface changed without regenerating. Run:\n  \
                 cargo xtask ts-sdk\n"
            );
            return Ok(ExitCode::FAILURE);
        }
        println!("sdk/typescript and proto/openapi.json match the schemas");
    } else {
        println!(
            "wrote proto/openapi.json and {} SDK files",
            outputs.len() - 1
        );
    }
    Ok(ExitCode::SUCCESS)
}

/// The CycloneDX SBOM (docs/20 M20.5).
///
/// Written to `sbom.cdx.json` at the repo root and checked in: an SBOM produced only at release
/// time answers "what did we ship" but not "what are we about to ship", and the second question is
/// the one a reviewer can act on.
fn sbom(check: bool) -> Result<ExitCode, String> {
    let root = repo_root();
    let path = root.join("sbom.cdx.json");
    let generated = sbom::generate(&root)?;

    if check {
        let existing = std::fs::read_to_string(&path).unwrap_or_default();
        if existing != generated.json {
            eprintln!(
                "sbom.cdx.json is stale — run `cargo xtask sbom` and commit the result\n\
                 (the lockfile and the SBOM disagree, which means the SBOM describes a build \
                 nobody is making)"
            );
            return Ok(ExitCode::FAILURE);
        }
        println!(
            "sbom.cdx.json matches the lockfile ({} components)",
            generated.components
        );
        return Ok(ExitCode::SUCCESS);
    }

    std::fs::write(&path, &generated.json).map_err(|e| format!("write {}: {e}", path.display()))?;
    println!(
        "wrote {} ({} components)",
        path.display(),
        generated.components
    );
    Ok(ExitCode::SUCCESS)
}

/// The weekly review artifact (docs/12 M12.4, docs/19 §gates).
///
/// > "Scorecard generator from eval runs; the weekly review is a generated PR against the
/// > YAML."
///
/// Two halves. This produces the *report*, from the evals that exist as libraries
/// (`panday_router::bench`, `panday_harness::eval`) — not by parsing test output, which breaks
/// the first time someone renames a test. `.github/workflows/weekly-review.yml` is the other
/// half: it runs this, commits the file, and opens the PR a human reviews.
///
/// What it deliberately does **not** do is edit the policy YAML itself. Removing a rule
/// changes where traffic goes, and a generator that did that silently would be the one
/// component in this repo making routing decisions nobody reviewed. It reports what the
/// linter found and leaves the edit in the PR's hands.
fn scorecard(write: bool) -> Result<ExitCode, String> {
    let root = repo_root();
    let mut out = String::new();
    let today = std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%d"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "undated".into());

    out.push_str(&format!("# Scorecard — {today}\n\n"));
    out.push_str(
        "Generated by `cargo xtask scorecard` (docs/12 M12.4). Every number here comes from an\n\
         eval that also gates CI, so this report and the test suite cannot disagree.\n\n",
    );

    // route-bench (docs/19's task-classification suite).
    out.push_str("## route-bench — task classification\n\n");
    let heuristic = panday_router::bench::score(&panday_router::classify::HeuristicClassifier);
    out.push_str("```\n");
    out.push_str(&heuristic.scorecard("heuristic"));
    out.push_str("```\n\n");
    out.push_str(&format!(
        "Gate (docs/19): accuracy >= 70% and never confidently wrong — **{}**.\n\n",
        if heuristic.meets_the_gate(0.70) {
            "pass"
        } else {
            "FAIL"
        }
    ));
    out.push_str(
        "The trained classifier (M19.3) must beat this by >=10pt on the same corpus; \
         `panday_router::shadow` is how a candidate is compared without letting it route.\n\n",
    );

    // The routing policy's own lint.
    out.push_str("## routing policy\n\n");
    for policy in ["default.yaml", "dev.yaml", "local.yaml"] {
        let path = root.join("crates/panday-router/policy").join(policy);
        let text =
            std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        match panday_router::Policy::from_yaml(&text) {
            Ok(parsed) => {
                let findings = parsed.lint();
                if findings.is_empty() {
                    out.push_str(&format!("- `{policy}`: no unreachable rules.\n"));
                } else {
                    out.push_str(&format!(
                        "- `{policy}`: **{} finding(s)**\n",
                        findings.len()
                    ));
                    for finding in findings {
                        out.push_str(&format!(
                            "  - rules[{}]: {}\n",
                            finding.rule_index, finding.message
                        ));
                    }
                }
            }
            Err(e) => out.push_str(&format!("- `{policy}`: **does not parse** — {e}\n")),
        }
    }
    out.push_str(
        "\nA finding here is a rule that can never fire, which means traffic is going \
         somewhere other than where the file says. The fix is a YAML edit, and it is left to \
         the human reading this PR — a generator that rewrote routing on its own would be the \
         one component here making a decision nobody reviewed.\n\n",
    );

    out.push_str("## reduce-bench — reduce-then-solve\n\n");
    out.push_str(
        "Run by `cargo xtask reduce-bench` (M15.5) and by the nightly job; it needs an async \
         runtime, so it is a separate task rather than a section here. Its gate — no recorded \
         task may become unsolvable — blocks release on its own.\n\n",
    );

    out.push_str("## what is not measured yet\n\n");
    out.push_str(
        "- `agent-bench` (M19.6): 50 verifiable repo tasks. Needs T3 (M14.5).\n\
         - `json-bench` (M19.1): the suite exists (`panday_harness::json_bench`, 200 fixtures) \
         and runs with `cargo xtask json-bench` against a gateway — but it needs a model, so no \
         number appears here. CI has neither a GPU nor a GGUF, and a suite that skipped would put \
         a green tick next to 'we did not measure'.\n\
         - Capability profiles (M18.4) ship **declared**, not measured; M19.2 measures them, \
         and until then every profile says `(estimated)` in the system prompt.\n",
    );

    print!("{out}");

    if write {
        let dir = root.join("scorecards");
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let path = dir.join(format!("{today}.md"));
        std::fs::write(&path, &out).map_err(|e| format!("{}: {e}", path.display()))?;
        eprintln!("wrote {}", path.display());
    }

    // The exit code is the gate, so a workflow can use it directly.
    Ok(if heuristic.meets_the_gate(0.70) {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    })
}

/// Rebuild the T1 demo components and copy them where the escape suite reads them.
///
/// The output is checked in on purpose (see `crates/panday-sandbox/tests/t1_wasm.rs`):
/// a suite that needed `wasm32-wasip2` and `cargo-component` installed would skip
/// itself on most machines, and a sandbox suite that skips itself is a sandbox
/// nobody is testing.
fn wasm_fixtures() -> Result<ExitCode, String> {
    const TARGET: &str = "wasm32-wasip2";
    let root = repo_root();
    let dest = root.join("crates/panday-sandbox/tests/fixtures");
    std::fs::create_dir_all(&dest).map_err(|e| e.to_string())?;

    for (dir, artifact) in [
        ("fixtures/demo-tool", "demo_tool.wasm"),
        ("fixtures/greedy-tool", "greedy_tool.wasm"),
        ("fixtures/demo-hook", "demo_hook.wasm"),
    ] {
        let crate_dir = root.join(dir);
        let status = std::process::Command::new(env!("CARGO"))
            .current_dir(&crate_dir)
            .args(["build", "--release", "--target", TARGET])
            .status()
            .map_err(|e| format!("{dir}: {e}"))?;
        if !status.success() {
            return Err(format!(
                "{dir}: build failed (is the {TARGET} target installed? \
                 `rustup target add {TARGET}`)"
            ));
        }
        let built = crate_dir
            .join("target")
            .join(TARGET)
            .join("release")
            .join(artifact);
        std::fs::copy(&built, dest.join(artifact))
            .map_err(|e| format!("copy {}: {e}", built.display()))?;
        println!("{} -> {}", built.display(), dest.join(artifact).display());
    }
    println!(
        "\nThe components are checked in; commit them with the change that \
         produced them so a reviewer sees both."
    );
    Ok(ExitCode::SUCCESS)
}

/// docs/15 M15.5: "nightly job + regression gate". The gate is the exit code.
fn reduce_bench(quiet: bool) -> ExitCode {
    // Delegating to the test binary rather than reimplementing the corpus here:
    // two copies of an eval corpus drift, and the copy the gate runs would be
    // the one nobody looks at.
    let status = std::process::Command::new(env!("CARGO"))
        .current_dir(repo_root())
        .args([
            "test",
            "-p",
            "panday-harness",
            "--test",
            "reduce_then_solve",
            "--",
            "--nocapture",
        ])
        .args(if quiet { vec!["--quiet"] } else { vec![] })
        .status();

    match status {
        Ok(s) if s.success() => ExitCode::SUCCESS,
        Ok(_) => {
            eprintln!(
                "\nreduce-bench FAILED — reduction made a recorded task unsolvable.\n\
                 docs/15: \"a reducer that loses the plot is negative value at any \
                 compression ratio\". This blocks release."
            );
            ExitCode::FAILURE
        }
        Err(e) => {
            eprintln!("reduce-bench: cannot run cargo test: {e}");
            ExitCode::FAILURE
        }
    }
}

fn repo_root() -> PathBuf {
    // xtask/ lives one level below the workspace root.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must live under the workspace root")
        .to_path_buf()
}

/// The schemas we publish, and where. Adding an entry here is all it takes to
/// export another type.
fn targets() -> Vec<(&'static str, schemars::Schema)> {
    vec![
        (
            "aep-envelope.schema.json",
            schemars::schema_for!(panday_types::Envelope),
        ),
        // docs/19 M19.1: the gate ("a model enters routing pools only with a scorecard") is only
        // enforceable if something other than a human can read one.
        (
            "scorecard.schema.json",
            schemars::schema_for!(panday_types::scorecard::Scorecard),
        ),
    ]
}

fn render(schema: &schemars::Schema) -> Result<String, String> {
    let mut s = serde_json::to_string_pretty(schema).map_err(|e| e.to_string())?;
    s.push('\n');
    Ok(s)
}

fn schemas(check: bool) -> Result<ExitCode, String> {
    let dir = repo_root().join("proto");
    std::fs::create_dir_all(&dir).map_err(|e| format!("create proto/: {e}"))?;

    let mut stale = Vec::new();
    for (name, schema) in targets() {
        let path = dir.join(name);
        let generated = render(&schema)?;

        if check {
            let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
            if on_disk != generated {
                stale.push(name);
            }
        } else {
            std::fs::write(&path, &generated).map_err(|e| format!("write {name}: {e}"))?;
            println!("wrote proto/{name}");
        }
    }

    if check && !stale.is_empty() {
        eprintln!(
            "proto/ is out of date: {stale:?}\n\n\
             The event protocol changed without regenerating its schema. Run:\n  \
             cargo xtask schemas\n\n\
             and include a version note per docs/03 §Versioning discipline — a\n\
             schema change without one is a breaking change nobody reviewed."
        );
        return Ok(ExitCode::FAILURE);
    }

    if check {
        println!("proto/ is up to date");
    }
    Ok(ExitCode::SUCCESS)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exported schema must describe every event kind this build knows.
    /// Without this, adding an `Event` variant that schemars silently skips
    /// would ship a schema that rejects valid traffic.
    #[test]
    fn schema_describes_every_known_event_tag() {
        let schema = serde_json::to_string(&schemars::schema_for!(panday_types::Envelope))
            .expect("schema serializes");

        let missing: Vec<&str> = panday_types::event::KNOWN_EVENT_TAGS
            .iter()
            .copied()
            .filter(|tag| !schema.contains(&format!("\"const\":\"{tag}\"")))
            .collect();

        assert!(
            missing.is_empty(),
            "these event kinds are missing from the exported schema: {missing:?}"
        );
    }

    /// Schema generation must be deterministic, or `--check` would flap in CI
    /// and every run would look like a protocol change.
    #[test]
    fn schema_generation_is_stable() {
        let a = render(&schemars::schema_for!(panday_types::Envelope)).unwrap();
        let b = render(&schemars::schema_for!(panday_types::Envelope)).unwrap();
        assert_eq!(a, b, "schema generation is not deterministic");
    }
}
