//! Repo automation. docs/02 §Toolchain: "`cargo xtask` pattern for codegen
//! (event-schema export, OpenAPI generation) instead of build.rs cleverness."
//!
//! ```text
//! cargo xtask schemas          # regenerate proto/
//! cargo xtask schemas --check  # fail if proto/ is stale (CI)
//! cargo xtask reduce-bench     # reduce-then-solve scorecard + regression gate
//! cargo xtask wasm-fixtures    # rebuild the checked-in T1 plugin components
//! cargo xtask scorecard        # the weekly review artifact (docs/12 M12.4, docs/19)
//! ```

use std::path::{Path, PathBuf};
use std::process::ExitCode;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (cmd, rest) = match args.split_first() {
        Some((c, r)) => (c.as_str(), r),
        None => {
            usage();
            return ExitCode::FAILURE;
        }
    };

    match cmd {
        "schemas" => {
            let check = rest.iter().any(|a| a == "--check");
            match schemas(check) {
                Ok(code) => code,
                Err(e) => {
                    eprintln!("xtask schemas: {e}");
                    ExitCode::FAILURE
                }
            }
        }
        // M15.5. A task rather than only a test so the nightly job has one thing
        // to run and one artifact to keep, and so a human can read the scorecard
        // without decoding `cargo test` output.
        "reduce-bench" => reduce_bench(rest.iter().any(|a| a == "--quiet")),
        // M14.4. The built components are checked in, so this is run by a human
        // when a fixture's source changes — not by CI, which must not need a wasm
        // toolchain to gate the sandbox.
        // M12.4. Calls the evals as libraries rather than parsing test output: a report
        // assembled from `cargo test` stdout breaks the first time someone renames a test.
        "scorecard" => match scorecard(rest.iter().any(|a| a == "--write")) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask scorecard: {e}");
                ExitCode::FAILURE
            }
        },
        // M20.5. Regenerated by a human when dependencies change and checked in, so a diff of
        // `sbom.cdx.json` in a PR is the dependency review; CI re-runs it with `--check` so the
        // file cannot drift from the lockfile.
        "sbom" => match sbom(rest.iter().any(|a| a == "--check")) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask sbom: {e}");
                ExitCode::FAILURE
            }
        },
        // M10.6. Generated from the schemas and the OpenAPI document, checked in, and re-checked
        // by CI: a protocol change that forgets the SDK breaks our build rather than a user's.
        "ts-sdk" => match ts_sdk(rest.iter().any(|a| a == "--check")) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask ts-sdk: {e}");
                ExitCode::FAILURE
            }
        },
        // M19.1. Needs a model, so it is never part of `just check`: a suite that skips when it
        // cannot measure reports a green tick for "we did not measure".
        "json-bench" => match json_bench(rest) {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask json-bench: {e}");
                ExitCode::FAILURE
            }
        },
        "wasm-fixtures" => match wasm_fixtures() {
            Ok(code) => code,
            Err(e) => {
                eprintln!("xtask wasm-fixtures: {e}");
                ExitCode::FAILURE
            }
        },
        "help" | "--help" | "-h" => {
            usage();
            ExitCode::SUCCESS
        }
        other => {
            eprintln!("unknown task: {other}\n");
            usage();
            ExitCode::FAILURE
        }
    }
}

fn usage() {
    eprintln!(
        "usage: cargo xtask <task>\n\n\
         tasks:\n  \
         schemas [--check]   export JSON Schema for the event protocol to proto/\n  \
         reduce-bench        run the reduce-then-solve eval; non-zero on regression\n  \
         wasm-fixtures       rebuild fixtures/*-tool into the T1 test fixtures\n  \
         scorecard [--write] the weekly eval scorecard; --write saves it under scorecards/\n  \
         sbom [--check]      write sbom.cdx.json from the lockfile; --check fails on drift\n  \
         ts-sdk [--check]    regenerate sdk/typescript/ and proto/openapi.json\n  \
         json-bench          schema-validity against a running gateway; needs a model\n"
    );
}

mod sbom;
mod sdk;
mod ts;

/// `json-bench` against a running gateway (docs/19 M19.1).
///
/// Against the *gateway*, not a provider: the eval exercises routing, caching and the adapter as
/// well as the model, which is docs/19's "three birds". The scorecard it writes is a committed
/// artifact, because a number nobody can point at later is a number nobody trusts.
fn json_bench(args: &[String]) -> Result<ExitCode, String> {
    let value = |flag: &str, default: &str| -> String {
        args.iter()
            .position(|a| a == flag)
            .and_then(|i| args.get(i + 1))
            .cloned()
            .unwrap_or_else(|| default.to_string())
    };
    let model = value("--model", "local/qwen3.5-4b");
    let base_url = value("--base-url", "http://127.0.0.1:8088");
    let at = value("--at", "unstamped");
    let quantization = args
        .iter()
        .position(|a| a == "--quantization")
        .and_then(|i| args.get(i + 1))
        .cloned();
    let write = args.iter().any(|a| a == "--write");

    let runtime = tokio::runtime::Runtime::new().map_err(|e| e.to_string())?;
    let card = runtime.block_on(async {
        // The gateway speaks the same dialect it accepts, so the eval reaches it with the same
        // client any customer would use (docs/11 M11.5) — no private path.
        let client = panday_sdk::providers::openai_compat::OpenAiCompatClient::new(
            &base_url,
            std::env::var("PANDAY_API_KEY").ok(),
        );
        let corpus = panday_harness::json_bench::corpus();
        let mut card = panday_harness::json_bench::run(
            &client,
            &panday_types::model::ModelRef(model.clone()),
            &model,
            &at,
            &corpus,
        )
        .await;
        // docs/19 §gates: "quantize → then eval". A scorecard that does not say which quantization
        // it measured cannot be compared to the artifact anyone actually runs.
        card.provenance.quantization = quantization;
        card
    });

    print!("{}", card.to_markdown());
    if write {
        let dir = repo_root().join("scorecards");
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let path = dir.join(format!(
            "json-bench-{}.json",
            card.subject.replace('/', "_")
        ));
        let mut json = serde_json::to_string_pretty(&card).map_err(|e| e.to_string())?;
        json.push('\n');
        std::fs::write(&path, json).map_err(|e| format!("write {}: {e}", path.display()))?;
        println!("\nwrote {}", path.display());
    }
    // Non-zero when the suite found nothing to measure, so a broken endpoint is not a silent pass.
    Ok(if card.cases > 0 {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    })
}

/// The generated TypeScript SDK and the OpenAPI document (docs/10 M10.6).
fn ts_sdk(check: bool) -> Result<ExitCode, String> {
    let root = repo_root();
    let envelope: serde_json::Value = {
        let path = root.join("proto/aep-envelope.schema.json");
        let raw = std::fs::read_to_string(&path).map_err(|e| {
            format!(
                "read {}: {e} — run `cargo xtask schemas` first",
                path.display()
            )
        })?;
        serde_json::from_str(&raw).map_err(|e| format!("{}: {e}", path.display()))?
    };

    let openapi = panday_gateway::openapi::document();
    let mut openapi_json = serde_json::to_string_pretty(&openapi).map_err(|e| e.to_string())?;
    openapi_json.push('\n');

    let mut outputs: Vec<(PathBuf, String)> = vec![(root.join("proto/openapi.json"), openapi_json)];
    for file in sdk::files(&envelope, &openapi)? {
        outputs.push((root.join("sdk/typescript").join(file.path), file.contents));
    }

    let mut stale = Vec::new();
    for (path, contents) in &outputs {
        if check {
            if std::fs::read_to_string(path).unwrap_or_default() != *contents {
                stale.push(path.display().to_string());
            }
            continue;
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create {}: {e}", parent.display()))?;
        }
        std::fs::write(path, contents).map_err(|e| format!("write {}: {e}", path.display()))?;
    }

    if check {
        if !stale.is_empty() {
            eprintln!(
                "the generated SDK is stale: {stale:?}\n\n\
                 The protocol or the HTTP surface changed without regenerating. Run:\n  \
                 cargo xtask ts-sdk\n"
            );
            return Ok(ExitCode::FAILURE);
        }
        println!("sdk/typescript and proto/openapi.json match the schemas");
    } else {
        println!(
            "wrote proto/openapi.json and {} SDK files",
            outputs.len() - 1
        );
    }
    Ok(ExitCode::SUCCESS)
}

/// The CycloneDX SBOM (docs/20 M20.5).
///
/// Written to `sbom.cdx.json` at the repo root and checked in: an SBOM produced only at release
/// time answers "what did we ship" but not "what are we about to ship", and the second question is
/// the one a reviewer can act on.
fn sbom(check: bool) -> Result<ExitCode, String> {
    let root = repo_root();
    let path = root.join("sbom.cdx.json");
    let generated = sbom::generate(&root)?;

    if check {
        let existing = std::fs::read_to_string(&path).unwrap_or_default();
        if existing != generated.json {
            eprintln!(
                "sbom.cdx.json is stale — run `cargo xtask sbom` and commit the result\n\
                 (the lockfile and the SBOM disagree, which means the SBOM describes a build \
                 nobody is making)"
            );
            return Ok(ExitCode::FAILURE);
        }
        println!(
            "sbom.cdx.json matches the lockfile ({} components)",
            generated.components
        );
        return Ok(ExitCode::SUCCESS);
    }

    std::fs::write(&path, &generated.json).map_err(|e| format!("write {}: {e}", path.display()))?;
    println!(
        "wrote {} ({} components)",
        path.display(),
        generated.components
    );
    Ok(ExitCode::SUCCESS)
}

/// The weekly review artifact (docs/12 M12.4, docs/19 §gates).
///
/// > "Scorecard generator from eval runs; the weekly review is a generated PR against the
/// > YAML."
///
/// Two halves. This produces the *report*, from the evals that exist as libraries
/// (`panday_router::bench`, `panday_harness::eval`) — not by parsing test output, which breaks
/// the first time someone renames a test. `.github/workflows/weekly-review.yml` is the other
/// half: it runs this, commits the file, and opens the PR a human reviews.
///
/// What it deliberately does **not** do is edit the policy YAML itself. Removing a rule
/// changes where traffic goes, and a generator that did that silently would be the one
/// component in this repo making routing decisions nobody reviewed. It reports what the
/// linter found and leaves the edit in the PR's hands.
fn scorecard(write: bool) -> Result<ExitCode, String> {
    let root = repo_root();
    let mut out = String::new();
    let today = std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%d"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "undated".into());

    out.push_str(&format!("# Scorecard — {today}\n\n"));
    out.push_str(
        "Generated by `cargo xtask scorecard` (docs/12 M12.4). Every number here comes from an\n\
         eval that also gates CI, so this report and the test suite cannot disagree.\n\n",
    );

    // route-bench (docs/19's task-classification suite).
    out.push_str("## route-bench — task classification\n\n");
    let heuristic = panday_router::bench::score(&panday_router::classify::HeuristicClassifier);
    out.push_str("```\n");
    out.push_str(&heuristic.scorecard("heuristic"));
    out.push_str("```\n\n");
    out.push_str(&format!(
        "Gate (docs/19): accuracy >= 70% and never confidently wrong — **{}**.\n\n",
        if heuristic.meets_the_gate(0.70) {
            "pass"
        } else {
            "FAIL"
        }
    ));
    out.push_str(
        "The trained classifier (M19.3) must beat this by >=10pt on the same corpus; \
         `panday_router::shadow` is how a candidate is compared without letting it route.\n\n",
    );

    // The routing policy's own lint.
    out.push_str("## routing policy\n\n");
    for policy in ["default.yaml", "dev.yaml", "local.yaml"] {
        let path = root.join("crates/panday-router/policy").join(policy);
        let text =
            std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        match panday_router::Policy::from_yaml(&text) {
            Ok(parsed) => {
                let findings = parsed.lint();
                if findings.is_empty() {
                    out.push_str(&format!("- `{policy}`: no unreachable rules.\n"));
                } else {
                    out.push_str(&format!(
                        "- `{policy}`: **{} finding(s)**\n",
                        findings.len()
                    ));
                    for finding in findings {
                        out.push_str(&format!(
                            "  - rules[{}]: {}\n",
                            finding.rule_index, finding.message
                        ));
                    }
                }
            }
            Err(e) => out.push_str(&format!("- `{policy}`: **does not parse** — {e}\n")),
        }
    }
    out.push_str(
        "\nA finding here is a rule that can never fire, which means traffic is going \
         somewhere other than where the file says. The fix is a YAML edit, and it is left to \
         the human reading this PR — a generator that rewrote routing on its own would be the \
         one component here making a decision nobody reviewed.\n\n",
    );

    out.push_str("## reduce-bench — reduce-then-solve\n\n");
    out.push_str(
        "Run by `cargo xtask reduce-bench` (M15.5) and by the nightly job; it needs an async \
         runtime, so it is a separate task rather than a section here. Its gate — no recorded \
         task may become unsolvable — blocks release on its own.\n\n",
    );

    out.push_str("## what is not measured yet\n\n");
    out.push_str(
        "- `agent-bench` (M19.6): 50 verifiable repo tasks. Needs T3 (M14.5).\n\
         - `json-bench` (M19.1): the suite exists (`panday_harness::json_bench`, 200 fixtures) \
         and runs with `cargo xtask json-bench` against a gateway — but it needs a model, so no \
         number appears here. CI has neither a GPU nor a GGUF, and a suite that skipped would put \
         a green tick next to 'we did not measure'.\n\
         - Capability profiles (M18.4) ship **declared**, not measured; M19.2 measures them, \
         and until then every profile says `(estimated)` in the system prompt.\n",
    );

    print!("{out}");

    if write {
        let dir = root.join("scorecards");
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let path = dir.join(format!("{today}.md"));
        std::fs::write(&path, &out).map_err(|e| format!("{}: {e}", path.display()))?;
        eprintln!("wrote {}", path.display());
    }

    // The exit code is the gate, so a workflow can use it directly.
    Ok(if heuristic.meets_the_gate(0.70) {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    })
}

/// Rebuild the T1 demo components and copy them where the escape suite reads them.
///
/// The output is checked in on purpose (see `crates/panday-sandbox/tests/t1_wasm.rs`):
/// a suite that needed `wasm32-wasip2` and `cargo-component` installed would skip
/// itself on most machines, and a sandbox suite that skips itself is a sandbox
/// nobody is testing.
fn wasm_fixtures() -> Result<ExitCode, String> {
    const TARGET: &str = "wasm32-wasip2";
    let root = repo_root();
    let dest = root.join("crates/panday-sandbox/tests/fixtures");
    std::fs::create_dir_all(&dest).map_err(|e| e.to_string())?;

    for (dir, artifact) in [
        ("fixtures/demo-tool", "demo_tool.wasm"),
        ("fixtures/greedy-tool", "greedy_tool.wasm"),
        ("fixtures/demo-hook", "demo_hook.wasm"),
    ] {
        let crate_dir = root.join(dir);
        let status = std::process::Command::new(env!("CARGO"))
            .current_dir(&crate_dir)
            .args(["build", "--release", "--target", TARGET])
            .status()
            .map_err(|e| format!("{dir}: {e}"))?;
        if !status.success() {
            return Err(format!(
                "{dir}: build failed (is the {TARGET} target installed? \
                 `rustup target add {TARGET}`)"
            ));
        }
        let built = crate_dir
            .join("target")
            .join(TARGET)
            .join("release")
            .join(artifact);
        std::fs::copy(&built, dest.join(artifact))
            .map_err(|e| format!("copy {}: {e}", built.display()))?;
        println!("{} -> {}", built.display(), dest.join(artifact).display());
    }
    println!(
        "\nThe components are checked in; commit them with the change that \
         produced them so a reviewer sees both."
    );
    Ok(ExitCode::SUCCESS)
}

/// docs/15 M15.5: "nightly job + regression gate". The gate is the exit code.
fn reduce_bench(quiet: bool) -> ExitCode {
    // Delegating to the test binary rather than reimplementing the corpus here:
    // two copies of an eval corpus drift, and the copy the gate runs would be
    // the one nobody looks at.
    let status = std::process::Command::new(env!("CARGO"))
        .current_dir(repo_root())
        .args([
            "test",
            "-p",
            "panday-harness",
            "--test",
            "reduce_then_solve",
            "--",
            "--nocapture",
        ])
        .args(if quiet { vec!["--quiet"] } else { vec![] })
        .status();

    match status {
        Ok(s) if s.success() => ExitCode::SUCCESS,
        Ok(_) => {
            eprintln!(
                "\nreduce-bench FAILED — reduction made a recorded task unsolvable.\n\
                 docs/15: \"a reducer that loses the plot is negative value at any \
                 compression ratio\". This blocks release."
            );
            ExitCode::FAILURE
        }
        Err(e) => {
            eprintln!("reduce-bench: cannot run cargo test: {e}");
            ExitCode::FAILURE
        }
    }
}

fn repo_root() -> PathBuf {
    // xtask/ lives one level below the workspace root.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must live under the workspace root")
        .to_path_buf()
}

/// The schemas we publish, and where. Adding an entry here is all it takes to
/// export another type.
fn targets() -> Vec<(&'static str, schemars::Schema)> {
    vec![
        (
            "aep-envelope.schema.json",
            schemars::schema_for!(panday_types::Envelope),
        ),
        // docs/19 M19.1: the gate ("a model enters routing pools only with a scorecard") is only
        // enforceable if something other than a human can read one.
        (
            "scorecard.schema.json",
            schemars::schema_for!(panday_types::scorecard::Scorecard),
        ),
    ]
}

fn render(schema: &schemars::Schema) -> Result<String, String> {
    let mut s = serde_json::to_string_pretty(schema).map_err(|e| e.to_string())?;
    s.push('\n');
    Ok(s)
}

fn schemas(check: bool) -> Result<ExitCode, String> {
    let dir = repo_root().join("proto");
    std::fs::create_dir_all(&dir).map_err(|e| format!("create proto/: {e}"))?;

    let mut stale = Vec::new();
    for (name, schema) in targets() {
        let path = dir.join(name);
        let generated = render(&schema)?;

        if check {
            let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
            if on_disk != generated {
                stale.push(name);
            }
        } else {
            std::fs::write(&path, &generated).map_err(|e| format!("write {name}: {e}"))?;
            println!("wrote proto/{name}");
        }
    }

    if check && !stale.is_empty() {
        eprintln!(
            "proto/ is out of date: {stale:?}\n\n\
             The event protocol changed without regenerating its schema. Run:\n  \
             cargo xtask schemas\n\n\
             and include a version note per docs/03 §Versioning discipline — a\n\
             schema change without one is a breaking change nobody reviewed."
        );
        return Ok(ExitCode::FAILURE);
    }

    if check {
        println!("proto/ is up to date");
    }
    Ok(ExitCode::SUCCESS)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exported schema must describe every event kind this build knows.
    /// Without this, adding an `Event` variant that schemars silently skips
    /// would ship a schema that rejects valid traffic.
    #[test]
    fn schema_describes_every_known_event_tag() {
        let schema = serde_json::to_string(&schemars::schema_for!(panday_types::Envelope))
            .expect("schema serializes");

        let missing: Vec<&str> = panday_types::event::KNOWN_EVENT_TAGS
            .iter()
            .copied()
            .filter(|tag| !schema.contains(&format!("\"const\":\"{tag}\"")))
            .collect();

        assert!(
            missing.is_empty(),
            "these event kinds are missing from the exported schema: {missing:?}"
        );
    }

    /// Schema generation must be deterministic, or `--check` would flap in CI
    /// and every run would look like a protocol change.
    #[test]
    fn schema_generation_is_stable() {
        let a = render(&schemars::schema_for!(panday_types::Envelope)).unwrap();
        let b = render(&schemars::schema_for!(panday_types::Envelope)).unwrap();
        assert_eq!(a, b, "schema generation is not deterministic");
    }
}
