//! The generated TypeScript SDK (M10.6).
//!
//! Two inputs, both already the source of truth for something else: `proto/*.schema.json` (the
//! event protocol, generated from the Rust types at M3.2) and `panday_gateway::openapi` (the HTTP
//! surface, living next to the handlers it describes). Nothing here is hand-written prose about
//! what the API *is* — that would be a third copy, and the third copy is always the wrong one.
//!
//! **Generated, never published.** `package.json` says `"private": true`. docs/10 lists a publish
//! pipeline; publishing is a decision with a name attached to it (an npm scope, a release cadence,
//! a deprecation policy), and shipping a package before those exist is how an unmaintained SDK ends
//! up as somebody's dependency. The generator is the part that had to exist first.

use serde_json::Value;

pub struct File {
    pub path: &'static str,
    pub contents: String,
}

const HEADER: &str = "// GENERATED by `cargo xtask ts-sdk`. Do not edit — regenerate.\n\
                      //\n\
                      // Source: the same schemas the Rust implementation is checked against, so a\n\
                      // protocol change that forgets this file fails CI rather than a user's build.\n\n";

/// Everything the SDK directory contains, in memory, so `--check` and `--write` cannot disagree
/// about what "generated" means.
pub fn files(envelope_schema: &Value, openapi: &Value) -> Result<Vec<File>, String> {
    let events = crate::ts::emit(envelope_schema, "Envelope", HEADER)?;

    // The OpenAPI component schemas share the JSON Schema subset the emitter already handles; the
    // only difference is where refs point, which `ref_name` reduces to the last segment either way.
    let components = openapi
        .get("components")
        .and_then(|c| c.get("schemas"))
        .cloned()
        .ok_or("the OpenAPI document has no component schemas")?;
    let mut api = String::from(HEADER);
    if let Some(schemas) = components.as_object() {
        for (name, schema) in schemas {
            api.push_str(&crate::ts::emit(schema, name, "")?);
        }
    }

    Ok(vec![
        File {
            path: "src/events.ts",
            contents: events,
        },
        File {
            path: "src/api.ts",
            contents: api,
        },
        File {
            path: "src/client.ts",
            contents: client(),
        },
        File {
            path: "src/index.ts",
            contents: format!(
                // Explicit `.ts` extensions: this package ships TypeScript *source* to be
                // vendored, not a build output, so the specifier has to name the file that is
                // actually there. Extension-less imports resolve only under a bundler's
                // conventions, and the package is meant to work without one.
                //
                // The event protocol is a namespace rather than a flat re-export, because the two
                // surfaces genuinely disagree: `Usage` in the HTTP dialect counts prompt and
                // completion tokens, `Usage` in the event log counts fresh input, cache reads and
                // cache writes (ADR-007). Flattening them would have to rename one, and a
                // generated name that does not match the protocol it came from is a trap.
                "{HEADER}export * from \"./api.ts\";\nexport * from \"./client.ts\";\n\
                 export * as aep from \"./events.ts\";\n"
            ),
        },
        File {
            path: "package.json",
            contents: package_json(),
        },
        File {
            path: "README.md",
            contents: readme(),
        },
    ])
}

/// The client. Small on purpose: `fetch`, an auth header, the error envelope, and SSE framing.
///
/// No retry, no backoff, no queue — the gateway already owns failover, circuit breaking and rate
/// limits (docs/11), and a client that retried on top of that would turn one 429 into five.
fn client() -> String {
    format!(
        r#"{HEADER}import type {{ ChatCompletion, ChatCompletionRequest, ErrorResponse }} from "./api.ts";

export interface PandayOptions {{
  /** e.g. http://127.0.0.1:8088 — no trailing slash. */
  baseUrl: string;
  /** `pnd_live_…` or `pnd_test_…`. Omit against a gateway running without auth. */
  apiKey?: string;
  /** Defaults to the global `fetch`. Injectable so a test does not need a server. */
  fetch?: typeof fetch;
}}

/** A refusal from the gateway, carrying the status the caller has to branch on. */
export class PandayError extends Error {{
  constructor(
    readonly status: number,
    readonly type: string,
    message: string,
  ) {{
    super(message);
    this.name = "PandayError";
  }}
}}

export class Panday {{
  #options: PandayOptions;

  constructor(options: PandayOptions) {{
    this.#options = options;
  }}

  /** A non-streaming completion. */
  async chat(request: ChatCompletionRequest): Promise<ChatCompletion> {{
    const response = await this.#post({{ ...request, stream: false }});
    return (await response.json()) as ChatCompletion;
  }}

  /**
   * A streaming completion, as an async iterator of raw SSE payloads.
   *
   * Yields parsed JSON chunks and stops at the `[DONE]` sentinel, which is consumed rather than
   * yielded: it is framing, not data, and a caller that had to recognise it would be parsing the
   * transport.
   */
  async *stream(request: ChatCompletionRequest): AsyncGenerator<unknown> {{
    const response = await this.#post({{ ...request, stream: true }});
    const body = response.body;
    if (!body) throw new PandayError(response.status, "api_error", "no response body");

    const reader = body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    for (;;) {{
      const {{ done, value }} = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, {{ stream: true }});

      // Frames are separated by a blank line. Split on that rather than on newlines, or a
      // multi-line frame is delivered as several broken ones.
      let boundary = buffer.indexOf("\n\n");
      while (boundary !== -1) {{
        const frame = buffer.slice(0, boundary);
        buffer = buffer.slice(boundary + 2);
        boundary = buffer.indexOf("\n\n");

        for (const line of frame.split("\n")) {{
          if (!line.startsWith("data:")) continue;
          const payload = line.slice(5).trim();
          if (payload === "[DONE]") return;
          yield JSON.parse(payload);
        }}
      }}
    }}
  }}

  async #post(request: ChatCompletionRequest): Promise<Response> {{
    const doFetch = this.#options.fetch ?? fetch;
    const headers: Record<string, string> = {{ "content-type": "application/json" }};
    if (this.#options.apiKey) headers.authorization = `Bearer ${{this.#options.apiKey}}`;

    const response = await doFetch(`${{this.#options.baseUrl}}/v1/chat/completions`, {{
      method: "POST",
      headers,
      body: JSON.stringify(request),
    }});

    if (!response.ok) {{
      // Every failure arrives in the same envelope, so this is the only error path.
      const body = (await response.json().catch(() => null)) as ErrorResponse | null;
      throw new PandayError(
        response.status,
        body?.error?.type ?? "api_error",
        body?.error?.message ?? response.statusText,
      );
    }}
    return response;
  }}
}}
"#
    )
}

fn package_json() -> String {
    // `private: true` is the enforcement, not the comment: `npm publish` refuses outright, so
    // "never published" survives someone running the obvious command.
    r#"{
  "name": "@panday/sdk",
  "version": "0.1.0",
  "private": true,
  "description": "Generated TypeScript client for the Panday gateway. Not published — see README.",
  "type": "module",
  "main": "src/index.ts",
  "types": "src/index.ts",
  "license": "MIT OR Apache-2.0",
  "files": ["src"]
}
"#
    .to_string()
}

fn readme() -> String {
    r#"# @panday/sdk

**Generated. Do not edit — run `cargo xtask ts-sdk`.**

Types come from the same two sources the Rust implementation is checked against:

- `proto/aep-envelope.schema.json` — the event protocol (docs/03), generated from the Rust types.
- `panday_gateway::openapi` — the HTTP surface, which lives next to the handlers it describes.

CI regenerates this directory and fails if it differs, so a protocol change that forgets the SDK
breaks the build rather than a user's.

## Not published

`package.json` sets `"private": true`, and that is deliberate rather than pending. Publishing is a
commitment with a name on it — an npm scope, a release cadence, a deprecation policy, somebody who
answers issues — and a package on a registry without those is how an unmaintained SDK becomes
somebody's dependency. The generator is the part that had to exist first; the publish pipeline is a
decision for whoever takes that on.

Until then, vendor it: copy `src/` into your project, or add this directory as a path dependency.
Imports carry explicit `.ts` extensions because what ships here is source rather than a build
output — the specifier names the file that is actually on disk, which is what Deno, Bun and a
bundler-free Node all need.

## Two namespaces, on purpose

The HTTP surface is exported flat; the event protocol is under `aep`. They collide honestly:
`Usage` in the HTTP dialect counts prompt and completion tokens, while `Usage` in the event log
counts fresh input, cache reads and cache writes separately (ADR-007, because those price
differently). Renaming one to flatten them would produce a generated name that does not match the
protocol it came from.

```ts
import { type ChatCompletion, aep } from "./src/index.ts";

const envelope: aep.Envelope = JSON.parse(line);
```

## Use

```ts
import { Panday } from "./src/index.ts";

const panday = new Panday({ baseUrl: "http://127.0.0.1:8088", apiKey: process.env.PANDAY_API_KEY });

const completion = await panday.chat({
  model: "auto", // let the router choose (docs/12)
  messages: [{ role: "user", content: "why is this test failing?" }],
});

for await (const chunk of panday.stream({ model: "auto", messages: [...] })) {
  // chunks arrive parsed; the `[DONE]` sentinel is consumed, not yielded
}
```

The client does no retrying on purpose: the gateway already owns failover, circuit breaking and
rate limits (docs/11), and a client retrying on top of that turns one 429 into five.
"#
    .to_string()
}
